name: univpn
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sliding_up_panel:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - images/background/background.jpg
    - images/background/2x/
    - images/background/3x/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-Black.ttf
          weight: 900

        - asset: fonts/Montserrat/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic

        - asset: fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700

        - asset: fonts/Montserrat/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800

        - asset: fonts/Montserrat/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic

        - asset: fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200

        - asset: fonts/Montserrat/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic

        - asset: fonts/Montserrat/Montserrat-Italic.ttf
          weight: 400
          style: italic

        - asset: fonts/Montserrat/Montserrat-Light.ttf
          weight: 300

        - asset: fonts/Montserrat/Montserrat-LightItalic.ttf
          weight: 300
          style: italic

        - asset: fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500

        - asset: fonts/Montserrat/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400

        - asset: fonts/Montserrat/Montserrat-Semibold.ttf
          weight: 600

        - asset: fonts/Montserrat/Montserrat-SemiboldItalic.ttf
          weight: 600
          style: italic

        - asset: fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100

        - asset: fonts/Montserrat/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic
